#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Feb 10, 2018 10:52:00 PM
import sys
import requests
import lookup

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import cryptoGUI_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Crypto_Lookup (root)
    cryptoGUI_support.init(root, top)

    root.mainloop()

w = None
def create_Crypto_Lookup(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Crypto_Lookup (w)
    cryptoGUI_support.init(w, top, *args, **kwargs)
    return (w, top)

def test(top):

    top.label_Price_usd.configure(text='''work''')

def destroy_Crypto_Lookup():
    global w
    w.destroy()
    w = None


class Crypto_Lookup:

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family Arial -size 24 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 16 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("900x900+417+19")
        top.title("Crypto Lookup")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.textBox_search = Text(top)
        self.textBox_search.place(relx=0.02, rely=0.02, relheight=0.04
                , relwidth=0.4)
        self.textBox_search.configure(background="white")
        self.textBox_search.configure(font="TkTextFont")
        self.textBox_search.configure(foreground="black")
        self.textBox_search.configure(highlightbackground="#d9d9d9")
        self.textBox_search.configure(highlightcolor="black")
        self.textBox_search.configure(insertbackground="black")
        self.textBox_search.configure(selectbackground="#000000")
        self.textBox_search.configure(selectforeground="black")
        self.textBox_search.configure(width=254)
        self.textBox_search.configure(wrap=WORD)

        self.button_Confirm = Button(top, command=self.buttonClick, text="Submit")
        self.button_Confirm.place(relx=0.45, rely=0.02, height=25, width=336)
        self.button_Confirm.configure(takefocus="")
        self.button_Confirm.configure(text='''Look Up''')
        # #########################################################################

        self.container = ttk.Frame(top)
        self.container.place(relx=0.02, rely=0.06, relheight=0.93, relwidth=0.97)

        self.container.configure(relief=GROOVE)
        self.container.configure(borderwidth="2")
        self.container.configure(relief=GROOVE)
        self.container.configure(width=625)

        self.label_name = LabelFrame(self.container)
        self.label_name.place(relx=0.02, rely=0.02, relheight=0.12
                , relwidth=0.43)
        self.label_name.configure(borderwidth="1")
        self.label_name.configure(font=font9)
        self.label_name.configure(foreground="#000000")
        self.label_name.configure(relief=FLAT)
        self.label_name.configure(text='''Name''')
        self.label_name.configure(background="#D9D9D9")
        self.label_name.configure(highlightbackground="#d9d9d9")
        self.label_name.configure(highlightcolor="black")
        self.label_name.configure(width=270)

        self.text_name = Text(self.label_name)
        self.text_name.place(relx=0.44, rely=0.27, relheight=0.59, relwidth=0.5)
        self.text_name.configure(background="#D9D9D9")
        self.text_name.configure(borderwidth="0")
        self.text_name.configure(font=font10)
        self.text_name.configure(foreground="black")
        self.text_name.configure(highlightbackground="#d9d9d9")
        self.text_name.configure(highlightcolor="black")
        self.text_name.configure(insertbackground="black")
        self.text_name.configure(relief=FLAT)
        self.text_name.configure(selectbackground="#c4c4c4")
        self.text_name.configure(selectforeground="black")
        self.text_name.configure(width=134)
        self.text_name.configure(wrap=WORD)

        self.label_symbol = LabelFrame(self.container)
        self.label_symbol.place(relx=0.5, rely=0.02, relheight=0.12
                , relwidth=0.48)
        self.label_symbol.configure(borderwidth="1")
        self.label_symbol.configure(font=font9)
        self.label_symbol.configure(foreground="black")
        self.label_symbol.configure(relief=FLAT)
        self.label_symbol.configure(text='''Symbol''')
        self.label_symbol.configure(background="#d9d9d9")
        self.label_symbol.configure(highlightbackground="#d9d9d9")
        self.label_symbol.configure(highlightcolor="black")
        self.label_symbol.configure(width=300)

        self.text_symbol = Text(self.label_symbol)
        self.text_symbol.place(relx=0.43, rely=0.27, relheight=0.59
                , relwidth=0.45)
        self.text_symbol.configure(background="#D9D9D9")
        self.text_symbol.configure(borderwidth="0")
        self.text_symbol.configure(font=font10)
        self.text_symbol.configure(foreground="black")
        self.text_symbol.configure(highlightbackground="#d9d9d9")
        self.text_symbol.configure(highlightcolor="black")
        self.text_symbol.configure(insertbackground="black")
        self.text_symbol.configure(selectbackground="#c4c4c4")
        self.text_symbol.configure(selectforeground="black")
        self.text_symbol.configure(width=134)
        self.text_symbol.configure(wrap=WORD)

        self.label_rank = LabelFrame(self.container)
        self.label_rank.place(relx=0.02, rely=0.16, relheight=0.14
                , relwidth=0.43)
        self.label_rank.configure(borderwidth="1")
        self.label_rank.configure(font=font9)
        self.label_rank.configure(foreground="black")
        self.label_rank.configure(relief=FLAT)
        self.label_rank.configure(text='''Rank''')
        self.label_rank.configure(background="#d9d9d9")
        self.label_rank.configure(highlightbackground="#d9d9d9")
        self.label_rank.configure(highlightcolor="black")
        self.label_rank.configure(width=270)

        self.text_rank = Text(self.label_rank)
        self.text_rank.place(relx=0.44, rely=0.24, relheight=0.64, relwidth=0.53)

        self.text_rank.configure(background="#D9D9D9")
        self.text_rank.configure(borderwidth="0")
        self.text_rank.configure(font=font10)
        self.text_rank.configure(foreground="black")
        self.text_rank.configure(highlightbackground="#d9d9d9")
        self.text_rank.configure(highlightcolor="black")
        self.text_rank.configure(insertbackground="black")
        self.text_rank.configure(selectbackground="#c4c4c4")
        self.text_rank.configure(selectforeground="black")
        self.text_rank.configure(width=144)
        self.text_rank.configure(wrap=WORD)

        self.label_Price_usd = LabelFrame(self.container)
        self.label_Price_usd.place(relx=0.5, rely=0.16, relheight=0.14
                , relwidth=0.48)
        self.label_Price_usd.configure(borderwidth="1")
        self.label_Price_usd.configure(font=font9)
        self.label_Price_usd.configure(foreground="black")
        self.label_Price_usd.configure(relief=FLAT)
        self.label_Price_usd.configure(text='''Price_usd''')
        self.label_Price_usd.configure(background="#d9d9d9")
        self.label_Price_usd.configure(highlightbackground="#d9d9d9")
        self.label_Price_usd.configure(highlightcolor="black")
        self.label_Price_usd.configure(width=300)

        self.text_price_usd = Text(self.label_Price_usd)
        self.text_price_usd.place(relx=0.43, rely=0.24, relheight=0.52
                , relwidth=0.55)
        self.text_price_usd.configure(background="#D9D9D9")
        self.text_price_usd.configure(borderwidth="0")
        self.text_price_usd.configure(font=font10)
        self.text_price_usd.configure(foreground="black")
        self.text_price_usd.configure(highlightbackground="#d9d9d9")
        self.text_price_usd.configure(highlightcolor="black")
        self.text_price_usd.configure(insertbackground="black")
        self.text_price_usd.configure(selectbackground="#c4c4c4")
        self.text_price_usd.configure(selectforeground="black")
        self.text_price_usd.configure(width=164)
        self.text_price_usd.configure(wrap=WORD)

        self.label_mkt_cap = LabelFrame(self.container)
        self.label_mkt_cap.place(relx=0.02, rely=0.33, relheight=0.14
                , relwidth=0.43)
        self.label_mkt_cap.configure(borderwidth="1")
        self.label_mkt_cap.configure(font=font9)
        self.label_mkt_cap.configure(foreground="black")
        self.label_mkt_cap.configure(relief=FLAT)
        self.label_mkt_cap.configure(text='''Mkt Cap''')
        self.label_mkt_cap.configure(background="#d9d9d9")
        self.label_mkt_cap.configure(highlightbackground="#d9d9d9")
        self.label_mkt_cap.configure(highlightcolor="black")
        self.label_mkt_cap.configure(width=270)

        self.text_Mkt_cap = Text(self.label_mkt_cap)
        self.text_Mkt_cap.place(relx=0.01, rely=0.24, relheight=0.61
                , relwidth=0.75)
        self.text_Mkt_cap.configure(background="#D9D9D9")
        self.text_Mkt_cap.configure(borderwidth="0")
        self.text_Mkt_cap.configure(font=font10)
        self.text_Mkt_cap.configure(foreground="black")
        self.text_Mkt_cap.configure(highlightbackground="#d9d9d9")
        self.text_Mkt_cap.configure(highlightcolor="black")
        self.text_Mkt_cap.configure(insertbackground="black")
        self.text_Mkt_cap.configure(selectbackground="#c4c4c4")
        self.text_Mkt_cap.configure(selectforeground="black")
        self.text_Mkt_cap.configure(width=124)
        self.text_Mkt_cap.configure(wrap=WORD)

        self.label_avail_supply = LabelFrame(self.container)
        self.label_avail_supply.place(relx=0.5, rely=0.33, relheight=0.14
                , relwidth=0.48)
        self.label_avail_supply.configure(borderwidth="1")
        self.label_avail_supply.configure(font=font9)
        self.label_avail_supply.configure(foreground="black")
        self.label_avail_supply.configure(relief=FLAT)
        self.label_avail_supply.configure(text='''Aviable Supply''')
        self.label_avail_supply.configure(background="#d9d9d9")
        self.label_avail_supply.configure(highlightbackground="#d9d9d9")
        self.label_avail_supply.configure(highlightcolor="black")
        self.label_avail_supply.configure(width=300)

        self.text_Aviable_Supply = Text(self.label_avail_supply)
        self.text_Aviable_Supply.place(relx=0.01, rely=0.24, relheight=0.61
                , relwidth=0.75)
        self.text_Aviable_Supply.configure(background="#D9D9D9")
        self.text_Aviable_Supply.configure(borderwidth="0")
        self.text_Aviable_Supply.configure(font=font10)
        self.text_Aviable_Supply.configure(foreground="black")
        self.text_Aviable_Supply.configure(highlightbackground="#d9d9d9")
        self.text_Aviable_Supply.configure(highlightcolor="black")
        self.text_Aviable_Supply.configure(insertbackground="black")
        self.text_Aviable_Supply.configure(selectbackground="#c4c4c4")
        self.text_Aviable_Supply.configure(selectforeground="black")
        self.text_Aviable_Supply.configure(width=154)
        self.text_Aviable_Supply.configure(wrap=WORD)

        self.label_total_supp = LabelFrame(self.container)
        self.label_total_supp.place(relx=0.02, rely=0.49, relheight=0.14
                , relwidth=0.43)
        self.label_total_supp.configure(borderwidth="1")
        self.label_total_supp.configure(font=font9)
        self.label_total_supp.configure(foreground="black")
        self.label_total_supp.configure(relief=FLAT)
        self.label_total_supp.configure(text='''Total Supply''')
        self.label_total_supp.configure(background="#d9d9d9")
        self.label_total_supp.configure(highlightbackground="#d9d9d9")
        self.label_total_supp.configure(highlightcolor="black")
        self.label_total_supp.configure(width=270)

        self.test_Total_supply = Text(self.label_total_supp)
        self.test_Total_supply.place(relx=0.01, rely=0.24, relheight=0.61
                , relwidth=0.75)
        self.test_Total_supply.configure(background="#D9D9D9")
        self.test_Total_supply.configure(borderwidth="0")
        self.test_Total_supply.configure(font=font10)
        self.test_Total_supply.configure(foreground="black")
        self.test_Total_supply.configure(highlightbackground="#d9d9d9")
        self.test_Total_supply.configure(highlightcolor="black")
        self.test_Total_supply.configure(insertbackground="black")
        self.test_Total_supply.configure(selectbackground="#c4c4c4")
        self.test_Total_supply.configure(selectforeground="black")
        self.test_Total_supply.configure(width=124)
        self.test_Total_supply.configure(wrap=WORD)

        self.label_Max_supp = LabelFrame(self.container)
        self.label_Max_supp.place(relx=0.5, rely=0.49, relheight=0.14
                , relwidth=0.48)
        self.label_Max_supp.configure(borderwidth="1")
        self.label_Max_supp.configure(font=font9)
        self.label_Max_supp.configure(foreground="black")
        self.label_Max_supp.configure(relief=FLAT)
        self.label_Max_supp.configure(text='''Max Supply''')
        self.label_Max_supp.configure(background="#d9d9d9")
        self.label_Max_supp.configure(highlightbackground="#d9d9d9")
        self.label_Max_supp.configure(highlightcolor="black")
        self.label_Max_supp.configure(width=300)

        self.test_max_supply = Text(self.label_Max_supp)
        self.test_max_supply.place(relx=0.01, rely=0.24, relheight=0.61
                , relwidth=0.75)
        self.test_max_supply.configure(background="#D9D9D9")
        self.test_max_supply.configure(borderwidth="0")
        self.test_max_supply.configure(font=font10)
        self.test_max_supply.configure(foreground="black")
        self.test_max_supply.configure(highlightbackground="#d9d9d9")
        self.test_max_supply.configure(highlightcolor="black")
        self.test_max_supply.configure(insertbackground="black")
        self.test_max_supply.configure(selectbackground="#c4c4c4")
        self.test_max_supply.configure(selectforeground="black")
        self.test_max_supply.configure(width=142)
        self.test_max_supply.configure(wrap=WORD)

        self.label_Changed_1hr = LabelFrame(self.container)
        self.label_Changed_1hr.place(relx=0.02, rely=0.66, relheight=0.14
                , relwidth=0.43)
        self.label_Changed_1hr.configure(borderwidth="1")
        self.label_Changed_1hr.configure(font=font9)
        self.label_Changed_1hr.configure(foreground="black")
        self.label_Changed_1hr.configure(relief=FLAT)
        self.label_Changed_1hr.configure(text='''Changed 1h''')
        self.label_Changed_1hr.configure(background="#d9d9d9")
        self.label_Changed_1hr.configure(highlightbackground="#d9d9d9")
        self.label_Changed_1hr.configure(highlightcolor="black")
        self.label_Changed_1hr.configure(width=270)

        self.text_changed_1hr = Text(self.label_Changed_1hr)
        self.text_changed_1hr.place(relx=0.44, rely=0.26, relheight=0.61
                , relwidth=0.41)
        self.text_changed_1hr.configure(background="#D9D9D9")
        self.text_changed_1hr.configure(borderwidth="0")
        self.text_changed_1hr.configure(font=font10)
        self.text_changed_1hr.configure(foreground="black")
        self.text_changed_1hr.configure(highlightbackground="#d9d9d9")
        self.text_changed_1hr.configure(highlightcolor="#000000")
        self.text_changed_1hr.configure(insertbackground="#000000")
        self.text_changed_1hr.configure(selectbackground="#c4c4c4")
        self.text_changed_1hr.configure(selectforeground="black")
        self.text_changed_1hr.configure(width=112)
        self.text_changed_1hr.configure(wrap=WORD)

        self.label_Changed_24hr = LabelFrame(self.container)
        self.label_Changed_24hr.place(relx=0.5, rely=0.66, relheight=0.14
                , relwidth=0.48)
        self.label_Changed_24hr.configure(borderwidth="1")
        self.label_Changed_24hr.configure(font=font9)
        self.label_Changed_24hr.configure(foreground="black")
        self.label_Changed_24hr.configure(relief=FLAT)
        self.label_Changed_24hr.configure(text='''Changed 24hr''')
        self.label_Changed_24hr.configure(background="#d9d9d9")
        self.label_Changed_24hr.configure(highlightbackground="#d9d9d9")
        self.label_Changed_24hr.configure(highlightcolor="black")
        self.label_Changed_24hr.configure(width=300)

        self.text_changed_24hr = Text(self.label_Changed_24hr)
        self.text_changed_24hr.place(relx=0.47, rely=0.26, relheight=0.61
                , relwidth=0.41)
        self.text_changed_24hr.configure(background="#D9D9D9")
        self.text_changed_24hr.configure(borderwidth="0")
        self.text_changed_24hr.configure(font=font10)
        self.text_changed_24hr.configure(foreground="black")
        self.text_changed_24hr.configure(highlightbackground="#d9d9d9")
        self.text_changed_24hr.configure(highlightcolor="black")
        self.text_changed_24hr.configure(insertbackground="black")
        self.text_changed_24hr.configure(selectbackground="#c4c4c4")
        self.text_changed_24hr.configure(selectforeground="black")
        self.text_changed_24hr.configure(width=122)
        self.text_changed_24hr.configure(wrap=WORD)

        self.label_Changed_7d = LabelFrame(self.container)
        self.label_Changed_7d.place(relx=0.24, rely=0.82, relheight=0.19
                , relwidth=0.48)
        self.label_Changed_7d.configure(borderwidth="1")
        self.label_Changed_7d.configure(font=font9)
        self.label_Changed_7d.configure(foreground="black")
        self.label_Changed_7d.configure(relief=FLAT)
        self.label_Changed_7d.configure(text='''Changed 7d''')
        self.label_Changed_7d.configure(background="#d9d9d9")
        self.label_Changed_7d.configure(highlightbackground="#d9d9d9")
        self.label_Changed_7d.configure(highlightcolor="black")
        self.label_Changed_7d.configure(width=300)

        self.text_changed_7D = Text(self.label_Changed_7d)
        self.text_changed_7D.place(relx=0.43, rely=0.38, relheight=0.49
                , relwidth=0.47)
        self.text_changed_7D.configure(background="#D9D9D9")
        self.text_changed_7D.configure(borderwidth="0")
        self.text_changed_7D.configure(font=("Arial", 24))
        self.text_changed_7D.configure(foreground="black")
        self.text_changed_7D.configure(highlightbackground="#d9d9d9")
        self.text_changed_7D.configure(highlightcolor="black")
        self.text_changed_7D.configure(insertbackground="black")
        self.text_changed_7D.configure(selectbackground="#c4c4c4")
        self.text_changed_7D.configure(selectforeground="black")
        self.text_changed_7D.configure(width=142)
        self.text_changed_7D.configure(wrap=NONE)

    def buttonClick(self):
        self.clearText()
        lookupStr = str(self.textBox_search.get(1.0,'end-1c'))
        print(lookupStr)
        currDict = lookup.openURL(lookupStr)

        self.showName(currDict)
        self.showSymbol(currDict)
        self.showRank(currDict)
        self.showPrice(currDict)
        self.showMktCap(currDict)
        self.showAvailableSupply(currDict)
        self.showTotalSupply(currDict)
        self.showMaxSupply(currDict)
        self.showChange1h(currDict)
        self.showChange24h(currDict)
        self.showChange7d(currDict)


        # id: "ethereum",
        # name: "Ethereum",
        # symbol: "ETH",
        # rank: "2",
        # price_usd: "831.709",
        # price_btc: "0.101299",
        # 24
        # h_volume_usd: "2753290000.0",
        # market_cap_usd: "81124260590.0",
        # available_supply: "97539236.0",
        # total_supply: "97539236.0",
        # max_supply: null,
        # percent_change_1h: "-1.51",
        # percent_change_24h: "-7.07",
        # percent_change_7d: "-13.29",
        # last_updated: "1518313152"

    def clearText(self):
        index1 = 0.0
        index2 = END

        self.text_name.replace(index1,index2," ")

        self.text_symbol.replace(index1,index2," ")
        self.text_rank.replace(index1,index2, " ")
        self.text_price_usd.replace(index1,index2," ")
        self.text_Mkt_cap.replace(index1,index2,"")
        self.text_Aviable_Supply.replace(index1,index2," ")
        self.test_Total_supply.replace(index1,index2, " ")
        self.test_max_supply.replace(index1,index2," ")
        self.text_changed_1hr.replace(index1,index2," ")
        self.text_changed_24hr.replace(index1,index2," ")
        self.text_changed_7D.replace(index1,index2," ")

    def showName(self,currDict):
        str = currDict['name']
        self.text_name.insert(END, str)

    def showSymbol(self,currDict):
        str = currDict['symbol']
        self.text_symbol.insert(END,str)

    def showRank(self,currDict):
        str = currDict['rank']
        self.text_rank.insert(END, str)

    def showPrice(self,currDict):
        str = currDict['price_usd']

    def showMktCap(self,currDict):
        str = currDict['market_cap_usd']
        self.text_Mkt_cap.insert(END,str)

    def showAvailableSupply(self,currDict):
        str = currDict['available_supply']

        self.text_Aviable_Supply.insert(END,str)


    def showTotalSupply(self,currDict):
        str = currDict['total_supply']

        self.test_Total_supply.insert(END, str)

    def showMaxSupply(self,currDict):
        str = currDict['max_supply']

        self.test_max_supply.insert(END,currDict['max_supply'])

    def showChange1h(self,currDict):
        str = currDict['percent_change_1h']

        self.text_changed_1hr.insert(END,str)

    def showChange24h(self,currDict):
        str = currDict['percent_change_24h']

        self.text_changed_24hr.insert(END, str)

    def showChange7d(self,currDict):
        str = currDict['percent_change_7d']

        self.text_changed_7D.insert(END,str)




if __name__ == '__main__':
    vp_start_gui()