#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Feb 10, 2018 09:41:44 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import cryptoGUI_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Crypto_Lookup (root)
    cryptoGUI_support.init(root, top)
    root.mainloop()

w = None
def create_Crypto_Lookup(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Crypto_Lookup (w)
    cryptoGUI_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Crypto_Lookup():
    global w
    w.destroy()
    w = None


class Crypto_Lookup:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font11 = "-family {Segoe UI} -size 22 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 16 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("643x656+415+15")
        top.title("Crypto Lookup")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.textBox_search = Text(top)
        self.textBox_search.place(relx=0.02, rely=0.02, relheight=0.04
                , relwidth=0.35)
        self.textBox_search.configure(background="white")
        self.textBox_search.configure(font="TkTextFont")
        self.textBox_search.configure(foreground="black")
        self.textBox_search.configure(highlightbackground="#d9d9d9")
        self.textBox_search.configure(highlightcolor="black")
        self.textBox_search.configure(insertbackground="black")
        self.textBox_search.configure(selectbackground="#000000")
        self.textBox_search.configure(selectforeground="black")
        self.textBox_search.configure(width=224)
        self.textBox_search.configure(wrap=WORD)

        self.button_Confirm = ttk.Button(top)
        self.button_Confirm.place(relx=0.39, rely=0.02, height=25, width=316)
        self.button_Confirm.configure(takefocus="")
        self.button_Confirm.configure(text='''Look Up''')

        self.TFrame1 = ttk.Frame(top)
        self.TFrame1.place(relx=0.02, rely=0.06, relheight=0.91, relwidth=0.97)
        self.TFrame1.configure(relief=GROOVE)
        self.TFrame1.configure(borderwidth="2")
        self.TFrame1.configure(relief=GROOVE)
        self.TFrame1.configure(width=625)

        self.label_name = LabelFrame(self.TFrame1)
        self.label_name.place(relx=0.02, rely=0.02, relheight=0.13
                , relwidth=0.43)
        self.label_name.configure(relief=GROOVE)
        self.label_name.configure(font=font9)
        self.label_name.configure(foreground="black")
        self.label_name.configure(text='''Name''')
        self.label_name.configure(background="#d9d9d9")
        self.label_name.configure(width=300)

        self.Text1 = Text(self.label_name)
        self.Text1.place(relx=0.44, rely=0.27, relheight=0.59, relwidth=0.5)
        self.Text1.configure(background="#D9D9D9")
        self.Text1.configure(borderwidth="0")
        self.Text1.configure(font=font11)
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(width=134)
        self.Text1.configure(wrap=WORD)

        self.label_symbol = LabelFrame(self.TFrame1)
        self.label_symbol.place(relx=0.5, rely=0.02, relheight=0.13
                , relwidth=0.48)
        self.label_symbol.configure(relief=GROOVE)
        self.label_symbol.configure(font=font9)
        self.label_symbol.configure(foreground="black")
        self.label_symbol.configure(text='''Symbol''')
        self.label_symbol.configure(background="#d9d9d9")
        self.label_symbol.configure(width=300)

        self.label_rank = LabelFrame(self.TFrame1)
        self.label_rank.place(relx=0.02, rely=0.17, relheight=0.14
                , relwidth=0.43)
        self.label_rank.configure(relief=GROOVE)
        self.label_rank.configure(font=font9)
        self.label_rank.configure(foreground="black")
        self.label_rank.configure(text='''Rank''')
        self.label_rank.configure(background="#d9d9d9")
        self.label_rank.configure(width=270)

        self.label_Price_usd = LabelFrame(self.TFrame1)
        self.label_Price_usd.place(relx=0.5, rely=0.17, relheight=0.14
                , relwidth=0.48)
        self.label_Price_usd.configure(relief=GROOVE)
        self.label_Price_usd.configure(font=font9)
        self.label_Price_usd.configure(foreground="black")
        self.label_Price_usd.configure(text='''Price_usd''')
        self.label_Price_usd.configure(background="#d9d9d9")
        self.label_Price_usd.configure(width=300)

        self.label_mkt_cap = LabelFrame(self.TFrame1)
        self.label_mkt_cap.place(relx=0.02, rely=0.33, relheight=0.14
                , relwidth=0.43)
        self.label_mkt_cap.configure(relief=GROOVE)
        self.label_mkt_cap.configure(font=font9)
        self.label_mkt_cap.configure(foreground="black")
        self.label_mkt_cap.configure(text='''Mkt Cap''')
        self.label_mkt_cap.configure(background="#d9d9d9")
        self.label_mkt_cap.configure(width=270)

        self.label_avail_supply = LabelFrame(self.TFrame1)
        self.label_avail_supply.place(relx=0.5, rely=0.33, relheight=0.14
                , relwidth=0.48)
        self.label_avail_supply.configure(relief=GROOVE)
        self.label_avail_supply.configure(font=font9)
        self.label_avail_supply.configure(foreground="black")
        self.label_avail_supply.configure(text='''Aviable Supply''')
        self.label_avail_supply.configure(background="#d9d9d9")
        self.label_avail_supply.configure(width=300)

        self.label_total_supp = LabelFrame(self.TFrame1)
        self.label_total_supp.place(relx=0.02, rely=0.5, relheight=0.14
                , relwidth=0.43)
        self.label_total_supp.configure(relief=GROOVE)
        self.label_total_supp.configure(font=font9)
        self.label_total_supp.configure(foreground="black")
        self.label_total_supp.configure(text='''Total Supply''')
        self.label_total_supp.configure(background="#d9d9d9")
        self.label_total_supp.configure(width=270)

        self.label_Max_supp = LabelFrame(self.TFrame1)
        self.label_Max_supp.place(relx=0.5, rely=0.5, relheight=0.14
                , relwidth=0.48)
        self.label_Max_supp.configure(relief=GROOVE)
        self.label_Max_supp.configure(font=font9)
        self.label_Max_supp.configure(foreground="black")
        self.label_Max_supp.configure(text='''Max Supply''')
        self.label_Max_supp.configure(background="#d9d9d9")
        self.label_Max_supp.configure(width=300)

        self.label_Changed_1hr = LabelFrame(self.TFrame1)
        self.label_Changed_1hr.place(relx=0.02, rely=0.67, relheight=0.14
                , relwidth=0.43)
        self.label_Changed_1hr.configure(relief=GROOVE)
        self.label_Changed_1hr.configure(font=font9)
        self.label_Changed_1hr.configure(foreground="black")
        self.label_Changed_1hr.configure(text='''Changed 1h''')
        self.label_Changed_1hr.configure(background="#d9d9d9")
        self.label_Changed_1hr.configure(width=270)

        self.label_Changed_24hr = LabelFrame(self.TFrame1)
        self.label_Changed_24hr.place(relx=0.5, rely=0.67, relheight=0.14
                , relwidth=0.48)
        self.label_Changed_24hr.configure(relief=GROOVE)
        self.label_Changed_24hr.configure(font=font9)
        self.label_Changed_24hr.configure(foreground="black")
        self.label_Changed_24hr.configure(text='''Changed 24hr''')
        self.label_Changed_24hr.configure(background="#d9d9d9")
        self.label_Changed_24hr.configure(width=300)

        self.label_Changed_7d = LabelFrame(self.TFrame1)
        self.label_Changed_7d.place(relx=0.24, rely=0.83, relheight=0.14
                , relwidth=0.48)
        self.label_Changed_7d.configure(relief=GROOVE)
        self.label_Changed_7d.configure(font=font9)
        self.label_Changed_7d.configure(foreground="black")
        self.label_Changed_7d.configure(text='''Changed 7d''')
        self.label_Changed_7d.configure(background="#d9d9d9")
        self.label_Changed_7d.configure(width=300)






if __name__ == '__main__':
    vp_start_gui()



